### ISSUE TITLE
SomeFileName.scala.html : File Not Found

### ISSUE THREAD

**Issue by addnab** [scoverage/scoverage-maven-plugin#14]
The generated Package report files (bootcamp.marsrover.html in this case) are pointing to the wrong location(Absolute instead of relative).

`<a href="/home/addnab/projects/bootcamp/src/main/scala/bootcamp/scrabble/Block.scala.html">`

It should be:-

`<a href="./home/addnab/projects/bootcamp/src/main/scala/bootcamp/scrabble/Block.scala.html">`

![screenshot from 2014-12-22 12 54 48](https://cloud.githubusercontent.com/assets/1926126/5522177/bdea78d6-89d9-11e4-86ff-f127febcb181.png)

**Comment by StarWindMoonCloud** [comment]
I had a similar issue, and 1.0.2 does not help.
Git repo: https://github.com/StarWindMoonCloud/scoverage-specs2-test

**Comment by gslowikowski** [comment]
``scalac-scoverage-plugin`` (used internally) does not support multiple source roots (implementation changed in 1.0.0 release IMO). It properly calculates relative paths for main source root. In Maven this is ``src/main/java``. Additional source roots may be added, but relative paths will not be calculated properly when generating report. In this issue case additional source root is added by ``net.alchim31.maven:scala-maven-plugin:add-source`` mojo. Because ``src/main/scala`` is the only source root (there is no ``src/main/java`` directory) it can be set as default source root. Additionally the same can be done with default test source root (this has no impact on scoverage plugin).

Add:
```xml
    <build>
        <sourceDirectory>${basedir}/src/main/scala</sourceDirectory>
        <testSourceDirectory>${basedir}/src/test/scala</testSourceDirectory>
...
    </build>
```
and remove:
```xml
                            <goal>add-source</goal>
```
from ``scala-maven-plugin`` configuration.

Multiple source roots have to be supported by ``scoverage-scalac-plugin``. @sksamuel, can you tell if and when it will be implemented?

**Comment by StarWindMoonCloud** [comment]
@gslowikowski , not sure if I understood correctly. 
But the change did not work for my case.
Refer to https://github.com/StarWindMoonCloud/scoverage-specs2-test/commit/91b6141a64e423151a3715c5f04f0a510cf0a26d#diff-600376dffeb79835ede4a0b285078036R38

**Comment by gslowikowski** [comment]
This has to be added in ``<build>`` tag directly, see https://github.com/scoverage/scoverage-maven-samples/blob/master/simple/scala-plugin-scala-2.11/pom.xml#L54 for example

**Comment by StarWindMoonCloud** [comment]
Still no luck, check https://github.com/StarWindMoonCloud/scoverage-specs2-test/commit/8c0742144187a1cfe8aee559495c5a0d8707ec85
and the generated link is as below: 
      <td>
        <a href="(empty)/Sample.scala.html">
          Sample
        </a>

**Comment by gslowikowski** [comment]
Your project works for me, I need more info. What is your OS, Maven and Java version? Attach Maven log from ``mvn clean scoverage:report -X`` execution, please. Before the last change I had exception, you didn't mention about exception. Anyway execution log would be very helpful.

**Comment by StarWindMoonCloud** [comment]
mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T01:29:23+08:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

And I did not see much useful info from the log, refer to http://pastebin.com/1AB81qvK

**Comment by gslowikowski** [comment]
This is probably another problem with ``scalac-scoverage-plugin`` - report links are not generated properly when source files structure does not fit package names. Move your file ``Sample.scala`` to ``com/qili`` subdirectory and check if it helps.

I wrote that it works for me before because it stopped throwing exception, I didn't check the links.

**Comment by StarWindMoonCloud** [comment]
You are right!
To me, the issue is resolved, thank you!

**Comment by gslowikowski** [comment]
Anyway this is not obvious limitation of ``scalac-scoverage-plugin`` and should be improved in the future.
