### ISSUE TITLE
Coverage for integration tests

### ISSUE THREAD

**Issue by jkbkrk** [scoverage/scoverage-maven-plugin#18]
Hi. Is it possible to run scoverage for tests run in maven's integration test phase? This could be done separately from unit tests. Regards.

**Comment by gslowikowski** [comment]
Two new mojos implemented: `integration-check` (http://scoverage.github.io/scoverage-maven-plugin/1.0.5-SNAPSHOT/integration-check-mojo.html) and `integration-report` (http://scoverage.github.io/scoverage-maven-plugin/1.0.5-SNAPSHOT/integration-report-mojo.html).
1.0.5-SNAPSHOT deployed to Sonatype snapshots repository. To use it add:
```xml
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```
to your project or (better) `~/.m2/settings.xml` file.

Implementation is trivial, but there are many side effects. What I've already found:
1. When plugin is added to `reporting` section, all reporting mojos are executed, there are three now: `report`, `integration-report` and `report-only`. There is no reason to execute all of them, `reportset` should be configured with only one of them:
```xml
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.0.5-SNAPSHOT</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>report</report>
                            <!-- or <report>integration-report</report> -->
                            <!-- or <report>report-only</report> -->
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
```
2. In `package` phase of forked `scoverage` Maven life cycle generated `jar` file contains instrumented classes. This `jar` file should not be used as a dependency (installed or deployed) in other projects. I found a way to overcome this, but `maven-jar-plugin` version `2.5+` is required (latest Maven versions use `2.4` by default).

Test and say if this is what you wanted, please.

**Comment by gslowikowski** [comment]
After this change overwriting prevention mechanism should work for all versions of all packaging plugins (provided they use '${project.build.finalName}' property for constructing file name. E.g. `2.5+` version of `maven-jar-plugin` is not required, older versions should work properly too. Additionally other packagings (`war`, `ejb`, etc.) should work.

**Comment by gslowikowski** [comment]
New `1.1.0-SNAPSHOT` snapshot deployed.

**Comment by jkrawczyk** [comment]
Thank you! Sorry for the delay. I was checking it earlier but I was getting some weird errors and didn't have time to investigate. If I find any issues I will let you know.

**Comment by gslowikowski** [comment]
`1.1.0` was already released.

**Comment by jkrawczyk** [comment]
Everything seems to work fine. I had some problems with report generation. I was receiving
`[ERROR] Failed to execute goal org.scoverage:scoverage-maven-plugin:1.1.0:report-only (default-cli) on project [project]: An error has occurred in SCoverage report generation: Report generation exception: No source root found for '[path]/src/main/scala/[package]/[class].scala' (source roots: '[path]/src/main/java/')`

I was trying to add scala source root using `scala-maven-plugin` and `build-helper-maven-plugin` add-source goal. Both ways didn't help. Finally I added missing `<sourceDirectory>src/main/scala</sourceDirectory>` tag and it worked.

I was debugging mvn build and I noticed that `scoverage-maven-plugin` was reading source roots from other MavenProject instance than `scala-maven-plugin/build-helper-maven-plugin` were writing to. I'm not Maven expert and I don't know how plugins should work but it looked suspicious.

**Comment by gslowikowski** [comment]
Generally, if you have only one source root (`src/main/scala` in this case), set it with `<sourceDirectory>` pom element. This is the simplest method. If you have more source roots, both `build-helper-maven-plugin:add-source` and `scala-maven-plugin:add-source` mojos should work.

Can you show, how did you configure `scala-maven-plugin` and `build-helper-maven-plugin` for adding sources?

Scoverage plugin gets different instance of `MavenProject` from Maven because of it's `<extensions>true</extensions>` definition element. All settings should be the same, there are some internal differences in classpaths (I don't know details).

**Comment by jkrawczyk** [comment]
I had configuration like:
```   
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <goals>
              <goal>add-source</goal>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

or

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.9.1</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/main/scala</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Thanks.

**Comment by gslowikowski** [comment]
Ignore my comment about `extensions`. I thought about `play2` custom packaging and `play2-maven-plugin`.

Anyway, you found interesting problem. I always used `<sourceDirectory>`, that's why I didn't see it.
`report` and `integration-report` mojos fork `scoverage` lifecycle and after returning from that cycle
`project.getExecutionProject()` returns the project from that lifecycle with added roots.

See:
https://github.com/scoverage/scoverage-maven-plugin/blob/scoverage-maven-plugin-1.1.0/src/main/java/org/scoverage/plugin/SCoverageReportMojo.java#L381

In `report-only` mojo there is no forked lifecycle and `project.getExecutionProject()` returns the project from the default cycle, not having additional source roots because `add-source` mojo was not executed in this cycle.
The simplest solution would be to fork default lifecycle up to `generate-sources` in `report-only` mojo, but I don't know if it is safe, what side effects would it have. It would have negative impact on performance for sure. I will test it.

**Comment by gslowikowski** [comment]
I will probably not change `report-only` mojo. Just add `generate-sources` before it.

**Comment by gslowikowski** [comment]
There is better solution. Use `mvn scoverage:report scoverage:check-only` instead of `mvn scoverage:check scoverage:report-only` and `mvn scoverage:integration-report scoverage:check-only` instead of `mvn scoverage:integration-check scoverage:report-only`. Checking mojos don't use source roots.

**Comment by pabloa** [comment]
still does not work. I can reproduce the problem with a scala project multimodule with several sources src/main/java and src/main/scala. In my case it does not find a file that exists in the project.

**Comment by gslowikowski** [comment]
@pabloa prepare test project, please.
