### ISSUE TITLE
Support for cleaner POM entries for excludePackages?

### ISSUE THREAD

**Issue by medge-tc** [scoverage/scoverage-maven-plugin#33]
Hello,

Was wondering if it would be possible to support the following style for the excludeFiles/excludePackages configuration:

```
<excludedPackages>
    com.myproj.some.pkg;
    com.myproj.some.other.pkg;
    com.myproj.Main
</excludedPackages>
```

In my opinion this is much more readable and manageable as this list grows. 

Any attempt to use this format currently fails because the newline and tab characters seem to be read as part of the class/package name and thus result in the class not being found.

Cheers!

**Comment by gslowikowski** [comment]
I thought about it.

Your proposal looks reasonable, but this is simple parameter now, passed to scalac compiler as is and I would like to keep it simple. Besides, the syntax should be the same in Maven, SBT and Gradle plugins. I don't think, SBT and Gradle developers would like to change it now.

In your example:
- the dots in you example match any character, not only a dot (package separator), `\.` means a dot character
- you could try something like `com.myproj\.(some\.pkg|some\.other\.pkg)` (WARNING - this syntax with pipes will not work with `scala-maven-plugin` because it interprets them as option separators, this works only with `sbt-compiler-maven-plugin`)
- if `Main` is class name, it will not work, because only package names are expected

More elegant Maven syntax would be like:
```xml
<excludedPackages>
    <excludedPackage>com.myproj.some.pkg</excludedPackage>
    <excludedPackage>com.myproj.some.other.pkg</excludedPackage>
    <excludedPackage>com.myproj.Main</excludedPackage>
</excludedPackages>
```
but list-type properties have one disadvantage in Maven - you cannot pass them from command line (with `-Dscoverage.excludedPackages=foo|bar`) so I prefer simple strings. Additionally, changing parameter type from String to list of Strings would be backward incompatible, so I will not do it.

I hope, you will understand my point of view.

BTW, do you really need so many exclusions?

**Comment by medge-tc** [comment]
Makes sense :) 

I have to note that com.myproj.Main is a class in the sample I gave and it is currently being excluded in the project I pulled it from.

And to your last question: probably not if my code organization was a bit better. The project was an Akka project and included a couple traits that were debug/trace oriented that were not mixed in during testing for simplicity.

Cheers!
