### ISSUE TITLE
Failed to execute goal org.scoverage:scoverage-maven-plugin:1.1.1:report (coverage) on project simpleScala: An error has occurred in SCoverage report generation: 

### ISSUE THREAD

**Issue by f9lz** [scoverage/scoverage-maven-plugin#38]
Failed to execute goal org.scoverage:scoverage-maven-plugin:1.1.1:report (coverage) on project simpleScala: An error has occurred in SCoverage report generation: Report generation exception: No source root found for '/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/scala/com/example/Dog.scala' (source roots: '/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/java/') -> [Help 1]

This is my plugin in the pom file:

<plugin>
             	<groupId>net.alchim31.maven</groupId>
  				<artifactId>scala-maven-plugin</artifactId>
  				<version>3.2.0</version>
  				<executions>
            	<execution>
                	<goals>
                    	<goal>compile</goal>
                         <goal>testCompile</goal>
                     </goals>
                 </execution>
             </executions>
             <configuration>
             	<checkMultipleScalaVersions>false</checkMultipleScalaVersions>
             	<sources>
             	<sourceDirectory>src/main/java</sourceDirectory>
             	<sourceDirectory>src/main/scala</sourceDirectory>
             	<testSourceDirectory>src/test/java</testSourceDirectory>
             	<testSourceDirectory>src/test/scala</testSourceDirectory>
             	</sources>
                	<jvmArgs>
                    	<jvmArg>-Xms64m</jvmArg>
                        <jvmArg>-Xmx1024m</jvmArg>
                    </jvmArgs>
              </configuration>
             </plugin>     

Why isnt the scoverage able to find my source directory?

**Comment by f9lz** [comment]
[pom2.txt](https://github.com/scoverage/scoverage-maven-plugin/files/461874/pom2.txt)

**Comment by gslowikowski** [comment]
Because `scala-maven-plugin` adds internally additional source root to compilation (see https://github.com/davidB/scala-maven-plugin/blob/3.2.0/src/main/java/scala_maven/ScalaCompileMojo.java#L27-L32 and https://github.com/davidB/scala-maven-plugin/blob/3.2.0/src/main/java/scala_maven/ScalaCompileMojo.java#L44-L48). This is very bad design decision IMO.

Scoverage plugin knows nothing about it and does not try to reproduce this wrong behaviour. 

`src/main/scala` should be added explicitly to project's source rootes. You can do it with [add-source mojo](http://davidb.github.io/scala-maven-plugin/add-source-mojo.html). Add it to `goals` section of `scala-maven-plugin`.

**Comment by f9lz** [comment]
Thanks! It works now!

**Comment by gslowikowski** [comment]
If you have only `src/main/scala` (no `src/main/java`) you can just set it as the only source root with:
```xml
    <build>
        <sourceDirectory>${basedir}/src/main/scala</sourceDirectory>
...
    </build>
```

If you have both, one of them has to added during the build, with a mojo like `add-source` above.
