### ISSUE TITLE
Unable to run scoverage goal(s) in multi-module project with inter-module dependencies

### ISSUE THREAD

**Issue by nvrs** [scoverage/scoverage-maven-plugin#51]
Hi,

I am trying to execute a scoverage goal directly, e.g. mvn scoverate:integration-report (scoverage is not attached to a specific phase of the lifecycle), but it's impossible to do so on a reactor with modules that have cross-dependencies. The reason seems to be that in the forked process, the reactor dependencies appear to be absent. 

On the other hand, if scoverage is attached to maven's lifecycle, tests are always run twice, at least with scalatest, which is very time consuming for us. A possible workaround for us, would be to execute maven clean install -DskipTests=true on the aggregator pom first and then mvn scoverate:integration-report on it. However, this is dangerous to be performed on any environment in general as SNAPSHOT artifacts will end up in maven's cache which could lead to difficult to track bugs etc.

Since i understand that the reactor issue is probably not easy to solve, may i suggest ignoring the flag -DskipTests=true so one could use scoverage attached to the maven lifecycle but without running the tests twice?

**Comment by gslowikowski** [comment]
Hi. Can you provide test project showing the problem?

**Comment by nvrs** [comment]
Hi, sure, i ll work on it now and get back to you asap.

**Comment by nvrs** [comment]
Hi, i have to admit i can't reproduce it on a simple project. So there is either an issue with the maven build of the real project (most probable case), or there's some weird interplay with another plugin, and / or the presence of java code in the mix that's compiled after scala.

Therefore, I ll close this issue and only re-open in case i can reliably reproduce.
Thanks

**Comment by nvrs** [comment]
I managed to reproduce it using [this simple project](https://github.com/nvrs/scoverage-reactor).

When checking out master, if you don't do a "mvn clean install" you can execute as expected without any errors "mvn scoverage:report" but if you attempt to do "mvn scoverage:integration-report" then the build for module-b will complain about not being able to resolve module-a and module-a:tests snapshot artifacts.

**Comment by gslowikowski** [comment]
`module-b` depends on `module-a:${project.version}:test-jar`.

When executing Scoverage lifecycle `scoverage-` prefix is being added to `finalName` property (`module-a` becomes `scoverage-module-a`) to avoid overwriting regular artifacts with instrumented ones. Of course tests are never instrumented, but the mechanism is general and changes the name of tests jar too.

As a result, when building `module-b`, Maven cannot find `module-a:${project.version}:test-jar` dependency because there is only `scoverage-module-a:${project.version}:test-jar`.

I must think, if and how this can be fixed.

**Comment by nvrs** [comment]
I see. What the above doesn't explain though is why scoverage:report mojo runs without any issues whereas :integration-report won't.

In any case, if you need any help i could try and have a look.

**Comment by gslowikowski** [comment]
Hi @nvrs. I'm returning to old open issues.

Many users are asking for a JaCoCo-like mode, where Scoverage does not fork a life cycle. This will be dangerous because users can accidentally deploy instrumented artifacts, but I will work on it.

For now, for your case, the best solution (without installing artifacts first) is to call:
```
mvn package scoverage:integration-report
```
`module-a`'s jar and test-jar dependencies are checked by Maven before Scoverage plugin code is executed and because `module-a` wasn't built without Scoverage, Maven cannot find required artifacts and fails. In forked Scoverage life cycle Scoverage plugin switches to instrumented version of `module-a` dependency, but it is done later, when Maven gets all the required dependencies and starts execution of this forked life cycle.

I'm closing this issue. Reopen it if you want to discuss this case further.

**Comment by gslowikowski** [comment]
Check [my comment](https://github.com/scoverage/scoverage-maven-plugin/issues/61#issuecomment-449659803) please.
